crop_mode: face_tracking
device: cuda
ffmpeg_crf: 23
ffmpeg_preset: fast
llm_model: llama-3.1-8b-instant
llm_provider: groq
max_clip_duration: 90
min_clip_duration: 30
num_clips: 3
output_resolution: 1080x1920
subtitle_color: '#13e150'
subtitle_font_size: 39
subtitle_stroke_color: black
subtitle_style: word_by_word
use_nvenc: false
whisper_model: base
